### ISSUE TITLE
Add option to send text on startup

### ISSUE THREAD

**Issue by thanasipantazides** [foxsi/ListenerLogger#1]
### Goal of this functionality

It would be nice if the logger could send a UDP packet (to a specified remote) when it starts (from the end of the constructor). There are a few uses for notifying the remote that it has started listening:

1. For a speed test, this startup message can be used to trigger the remote to start sending.
2. For an integrity test, this is more important---need to make sure all sent packets are received.
3. This could trigger more complex behavior in the Formatter.
4. Can also send() in destructor. Then data exchange gets bookended/confirmed by receiver.

### Todo list

- [x] Add remote IP, port, endpoint attributes of `UDPListenerLogger`.
- [x] Implement `UDPListenerLogger::send()` method. No need to be asynchronous.
- [x] Add remote IP, port, and startup send message as command line arguments in `variables_map`.
- [x] Add setup of remote IP, port, endpoint to `UDPListenerLogger::configure()`.
