### ISSUE TITLE
Handle exceptions properly

### ISSUE THREAD

**Issue by thanasipantazides** [foxsi/ListenerLogger#5]
### The concerns

It is important to run `~UDPListenerLogger()` (the destructor) at the end of a logging run in order to:

1. Close the log file correctly
2. Cancel ongoing asynchronous traffic on `.local_socket_`
3. Report summary statistics etc for the log run

Currently, exceptions are thrown if `UDPListenerLogger::configure(...)` encounters errors opening the log file, opening sockets, etc. These are caught in `main`, which guarantees the destructor will run as expected. 

Some of these exceptions return a placeholder `char*` string, and some return an instance of (overloaded) `std::exception`. **All these exceptions should inherit from std::exception** and get handled appropriately.

### Todo

- [ ] Define a new class for custom exceptions
- [ ] Define `.what()` for these
- [ ] Make sure exceptions are being used how they should, not just for control flow.
